### ISSUE TITLE
Error after selecting guild

### ISSUE THREAD

**Issue by ghost** [KararTY/PruneMyDiscord#6]
Authenticated correctly. The script crashed after selecting guild (tried on various ones, still the same error).

```/root/PruneMyDiscord/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: answer.filter(...).map(...).flat is not a function
    at SafeSubscriber.onAnswer [as _next] (/root/PruneMyDiscord/initialize.js:221:106)
    at SafeSubscriber.__tryOrUnsub (/root/PruneMyDiscord/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/root/PruneMyDiscord/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/root/PruneMyDiscord/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/root/PruneMyDiscord/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/root/PruneMyDiscord/node_modules/rxjs/internal/Subject.js:60:25)
    at ConnectableSubscriber.Subscriber._next (/root/PruneMyDiscord/node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (/root/PruneMyDiscord/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/root/PruneMyDiscord/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/root/PruneMyDiscord/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prunemydiscord@2.0.1 start: `node ./initialize.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prunemydiscord@2.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-29T19_46_07_309Z-debug.log```

**Comment by KararTY** [comment]
What version of Node are you running?

**Comment by ghost** [comment]
{ npm: '6.14.4',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

**Comment by KararTY** [comment]
This script doesn't work on older NodeJS, due to breaking changes.

You need NodeJS LTS (12.16.3) or a later version.
![image](https://user-images.githubusercontent.com/13697809/80642237-6a1ffd00-8a66-11ea-9d76-f4668d4b4ff3.png)

**Comment by KararTY** [comment]
Please leave a reply if you're still having issues, otherwise I'll close this issue on Monday.

Thank you.

**Comment by ghost** [comment]
Works after NodeJS update, thanks!
